name: CI Toolkit
description: A toolkit for your CI builds.
author: https://github.com/automattic
requirements: ["awscli"]
configuration:
  properties:
    bucket:
      type: string
  additionalProperties: false
