name: CI Toolkit
description: A library of commonly used commands for your CI builds.
author: https://github.com/automattic
requirements:
  - aws
  - gh
  - jq
  - node
  - nvm
  - ruby
  - xcodebuild
  - xcrun
configuration:
  properties:
    bucket:
      type: string
  additionalProperties: false
