name: CI Toolkit
description: A library of commonly used commands for your CI builds.
author: https://github.com/automattic
requirements: ["awscli"]
configuration:
  properties:
    bucket:
      type: string
  additionalProperties: false
