generate:
	# Note: we need to copy the project file in place (as opposed to using --spec)
	# so that xcodegen can add the scheme for the Demo project into the `Demo.xcworkspace`
	cp ../project/project.yml .
	xcodegen generate
