# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# For convenience with the many install_swiftpm_dependencies steps, we declare agents and env for macOS in the root, then specialize the fewer remaining steps
agents:
  queue: windows

steps:
  - label: ":c: :windows: Test get_libc_version on Windows"
    command: |
      & "C:\Program Files\Git\bin\bash.exe" .\tests\validate_get_libc_version_format
    agents:
      queue: windows
