# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# For convenience with the many install_swiftpm_dependencies steps, we declare agents and env for macOS in the root, then specialize the fewer remaining steps
agents:
  queue: mac
env:
  IMAGE_ID: xcode-15.4

steps:
  - label: ":sleuth_or_spy: Lint"
    command: make lint
    notify:
      - github_commit_status:
          context: Lint
    agents:
      queue: default

  - label: ":microscope: Test"
    command: make test
    notify:
      - github_commit_status:
          context: Test
    agents:
      queue: default

  - label: ":radioactive_sign: Danger - PR Check"
    command: danger
    key: danger
    if: build.pull_request.id != null
    retry:
      manual:
        permit_on_passed: true
    notify:
      - github_commit_status:
          context: Danger - PR Check
    agents:
      queue: linter

  - group: ":swift: install_swiftpm_dependencies Tests"
    steps:
      - label: ":swift: Standalone Swift Package - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_package_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Standalone Swift Package - Autodetect"

      - label: ":swift: Standalone Swift Package - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_package_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Standalone Swift Package - Explicit"

      - label: ":xcode: Xcode Project - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_project_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Project - Autodetect"

      - label: ":xcode: Xcode Project - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_project_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Project - Explicit"

      - label: ":xcode: Xcode Project - No Package.resolved"
        command: tests/install_swiftpm_dependencies/test_scripts/test_project_no_package.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Project - No Package.resolved"

      - label: ":xcode: Xcode Workspace - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace - Autodetect"

      - label: ":xcode: Xcode Workspace - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace - Explicit"

      - label: ":xcode: Xcode Workspace and Project - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_and_project_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace and Project - Autodetect"

      - label: ":xcode: Xcode Workspace and Project - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_and_project_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace and Project - Explicit"

  - group: ":github: pr_changed_files Tests"
    steps:
      - label: ":github: pr_changed_files Tests - Basic Changes"
        command: tests/pr_changed_files/test_basic_changes.sh
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: Basic Changes"

      - label: ":github: pr_changed_files Tests - Any Match"
        command: tests/pr_changed_files/test_any_match_patterns.sh
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: Any Match"

      - label: ":github: pr_changed_files Tests - All Match"
        command: tests/pr_changed_files/test_all_match_patterns.sh
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: All Match"

      - label: ":github: pr_changed_files Tests - Edge Cases"
        command: tests/pr_changed_files/test_edge_cases.sh
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: Edge Cases"

  - group: ":windows: install_windows_10_sdk Tests"
    steps:
      - label: ":windows: install_windows_10_sdk Tests - Standard version file"
        command: |
          echo '20348' > .windows-10-sdk-version
          $output = & bin/install_windows_10_sdk.ps1 -DryRun
          $exitCode = $LASTEXITCODE
          if ($exitCode -ne 0) {
            echo "Unexpected failure. Exit code: $exitCode"
            echo "Output:"
            echo $output
            exit 1
          }
        agents:
          queue: windows
        notify:
          - github_commit_status:
              context: "install_windows_10_sdk Tests - Standard version file"

      - label: ":windows: install_windows_10_sdk Tests - Version file with new lines"
        command: |
          echo "20348`n`n" > .windows-10-sdk-version
          $output = & bin/install_windows_10_sdk.ps1 -DryRun
          $exitCode = $LASTEXITCODE
          if ($exitCode -ne 0) {
            echo "Unexpected failure. Exit code: $exitCode"
            echo "Output:"
            echo $output
            exit 1
          }
          if (($output -notmatch "[!] Invalid version file format") -and ($output -notmatch "Expected exactly one non-empty line")) {
            echo "Failure message did not match expectation."
            exit 1
          }
        agents:
          queue: windows
        notify:
          - github_commit_status:
              context: "install_windows_10_sdk Tests - Version file with new lines"

      - label: ":windows: install_windows_10_sdk Tests - Version file with a word"
        command: |
          echo "not an integer" > .windows-10-sdk-version
          $output = & bin/install_windows_10_sdk.ps1 -DryRun
          $exitCode = $LASTEXITCODE
          if ($exitCode -ne 1) {
            echo "Expected exit code 1, got: $exitCode"
            echo "Output:"
            echo $output
            exit 1
          }
          if (($output -notmatch "[!] Invalid version file format") -and ($output -notmatch "Expected an integer, got:'")) {
            echo "Failure message did not match expectation."
            exit 1
          }
        agents:
          queue: windows
        notify:
          - github_commit_status:
              context: "install_windows_10_sdk Tests - Version file with a word"
