# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# For convenience with the many install_swiftpm_dependencies steps, we declare agents and env for macOS in the root, then specialize the fewer remaining steps
agents:
  queue: mac
env:
  IMAGE_ID: xcode-15.4

steps:
  - group: ":c: get_libc_version Tests"
    steps:
      - label: ":c: Test get_libc_version on {{matrix}}"
        command: ./tests/validate_get_libc_version_format
        agents:
          queue: "{{matrix}}"
        matrix:
          - android
          - default
          - mac
          - tumblr-metal
          # Could not find a way to run on Windows with the same call as the others.
          # See syntax in the dedicated step in pipeline-windows-tests.yml.
          # - windows

  - group: ":swift: install_swiftpm_dependencies Tests"
    steps:
      - label: ":swift: Standalone Swift Package - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_package_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Standalone Swift Package - Autodetect"

      - label: ":swift: Standalone Swift Package - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_package_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Standalone Swift Package - Explicit"

      - label: ":xcode: Xcode Project - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_project_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Project - Autodetect"

      - label: ":xcode: Xcode Project - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_project_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Project - Explicit"

      - label: ":xcode: Xcode Project - No Package.resolved"
        command: tests/install_swiftpm_dependencies/test_scripts/test_project_no_package.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Project - No Package.resolved"

      - label: ":xcode: Xcode Workspace - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace - Autodetect"

      - label: ":xcode: Xcode Workspace - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace - Explicit"

      - label: ":xcode: Xcode Workspace and Project - Autodetect"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_and_project_automatic.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace and Project - Autodetect"

      - label: ":xcode: Xcode Workspace and Project - Explicit"
        command: tests/install_swiftpm_dependencies/test_scripts/test_workspace_and_project_explicit.sh
        notify:
          - github_commit_status:
              context: "install_swiftpm_dependencies Tests: Xcode Workspace and Project - Explicit"

  - group: ":github: pr_changed_files Tests"
    steps:
      - label: ":github: pr_changed_files Tests - Basic Changes"
        command: tests/pr_changed_files/test_basic_changes.sh
        agents:
          queue: "{{matrix}}"
        matrix:
          - android
          - default
          - mac
          - tumblr-metal
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: Basic Changes"

      - label: ":github: pr_changed_files Tests - Any Match"
        command: tests/pr_changed_files/test_any_match_patterns.sh
        agents:
          queue: "{{matrix}}"
        matrix:
          - android
          - default
          - mac
          - tumblr-metal
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: Any Match"

      - label: ":github: pr_changed_files Tests - All Match"
        command: tests/pr_changed_files/test_all_match_patterns.sh
        agents:
          queue: "{{matrix}}"
        matrix:
          - android
          - default
          - mac
          - tumblr-metal
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: All Match"

      - label: ":github: pr_changed_files Tests - Edge Cases"
        command: tests/pr_changed_files/test_edge_cases.sh
        agents:
          queue: "{{matrix}}"
        matrix:
          - android
          - default
          - mac
          - tumblr-metal
        notify:
          - github_commit_status:
              context: "pr_changed_files Tests: Edge Cases"

  - group: ":closed_lock_with_key: install_a8c-secrets_binary Integration Tests"
    steps:
      - label: ":linux: Install and run a8c-secrets"
        command: tests/install_a8c-secrets_binary/test_install.sh
        agents:
          queue: default
        notify:
          - github_commit_status:
              context: "install_a8c-secrets_binary Tests: Linux"

      - label: ":apple: Install and run a8c-secrets"
        command: tests/install_a8c-secrets_binary/test_install.sh
        agents:
          queue: mac
        notify:
          - github_commit_status:
              context: "install_a8c-secrets_binary Tests: macOS"
