steps:
  - label: ":shell: Lint (Shellcheck)"
    plugins:
      shellcheck#v1.2.0:
        files: ["hooks/**", "bin/**"]
        options: "-e SC1071" # Ignore scripts that are not written in bash (especially ruby scripts)

  - label: ":sparkles: Lint (Buildkite Plugin Linter)"
    plugins:
      plugin-linter#v2.0.0:
        id: automattic/bash-cache

  - label: ":docker: Test"
    plugins:
      docker-compose#v3.7.0:
        run: tests
