steps:
  - label: ":shell: Lint (Shellcheck)"
    command: make shellcheck

  - label: ":sparkles: Lint (Buildkite Plugin Linter)"
    command: make lint

  - label: ":docker: Test"
    command: make test
