#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# This repo is not an Xcode project, so we hardcode the version here rather than
# using a `.xcode-version` file like our Apple projects do.
XCODE_VERSION=26.6

export IMAGE_ID="xcode-$XCODE_VERSION"
