#!/bin/bash

# The `pre-command` hook will run just before your build command runs

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -e

echo "~~~ :file_cabinet: Loading Automattic plugin commands in the environment"

HOOKS_ROOT=$( dirname "${BASH_SOURCE[0]}" )
PLUGIN_ROOT=$( dirname "$HOOKS_ROOT" )

OS=$(uname -s)
case $OS in
  CYGWIN*|MINGW*|MSYS*)
    echo "Running in a Windows environment."
    PATH_SEPARATOR="\\"
    ;;
  *)
    echo "Running in a non-Windows environment."
    PATH_SEPARATOR='/'
    ;;
esac

PLUGIN_BIN="${PLUGIN_ROOT}${PATH_SEPARATOR}bin"

export PATH="$PATH:$PLUGIN_BIN"
echo "PATH updated to $PATH"
